version: '3.4'

networks:
  dev:
  driver: brigde

services:
  shopapp:
     image: docker.io/library/shopapp
     depends_on:
       - "app_db"
     ports:
       - "8080:80"
     container_name: shopapp_Services
     build:
       context: .
       dockerfile: Dockerfile
     environment:
       - ConnectionStrings_DefaultConnect=User ID=user;Password=password;Server=app_db;Port:5432;Database=store;IntegratedSecurity=true;Pooling=true;
       - ASPNETCORE_URLS=http://+:80
     networks:
       - dev

  app_db:
     image: postgres:latest
     container_name: app_db
     environment:
       - POSTGRES_USER=postgres
       - POSTGRES_PASSWORD= password
       - POSTGRES_DB=store
     ports:
       - "5433:5432"
     restart: always
     volume:
       - app_data:/var/lib/postgresql/data
     networks:
       - dev

volume:
  app_data
    
