apiVersion: apps/v1
kind: Deployment
metadata:
  name: eedconsultsofftextra
  labels:
    app: eedconsultsofftextra
  namespace: namespace-workflow-1711219322159
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eedconsultsofftextra
  template:
    metadata:
      labels:
        app: eedconsultsofftextra
    spec:
      containers:
        - name: eedconsultsofftextra
          image: acrworkflow1711219322159.azurecr.io/image-workflow-1711219322159:latest
          ports:
            - containerPort: 5000