apiVersion: v1
kind: Service
metadata:
  name: eedconsultkts
  namespace: namespace-workflow-1711217598506
spec:
  type: LoadBalancer
  selector:
    app: eedconsultkts
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000