apiVersion: v1
kind: Service
metadata:
  name: eedconsultsofftextra
  namespace: namespace-workflow-1711219322159
spec:
  type: LoadBalancer
  selector:
    app: eedconsultsofftextra
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000